# Generated by Django 5.2.12 on 2026-04-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Headings',
            new_name='Heading',
        ),
    ]
