# Generated by Django 5.2.12 on 2026-04-09 11:00

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.blog.models.category_thumbnail_directory),
        ),
    ]
