# Generated by Django 5.2.12 on 2026-04-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_views_postview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postview',
            name='timestamp',
        ),
    ]
