# Generated by Django 5.2.12 on 2026-04-18 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_heading_post_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_view', to='blog.post'),
        ),
    ]
